#!/bin/bash
mkdir -p web_flask/static/styles
mkdir -p web_flask/static/images
cp web_static/styles/3-footer.css web_flask/static/styles
cp web_static/styles/3-header.css web_flask/static/styles
cp web_static/styles/4-common.css web_flask/static/styles
cp web_static/styles/6-filters.css web_flask/static/styles

cp web_static/images/icon.png web_flask/static/images
cp web_static/images/logo.png web_flask/static/images
